### ISSUE TITLE
per_page param in searches

### ISSUE THREAD

**Issue by bigardone** [edgurgel/tentacat#109]
Hi! 
I'm trying to add the `per_page` param to the `Tentacat.Search.users` request but no options can be passed for that. Is there any other way of doing it? 
I have seen this PR #106 which seems to add this, but it hasn't be merged. Are you planning to merge it?
Thanks in advance

**Comment by edgurgel** [comment]
Yes I'm planning to merge soon!

**Comment by bigardone** [comment]
Cool, thanks!
