### ISSUE TITLE
support for removing a label from an issue

### ISSUE THREAD

**Issue by SimonLab** [edgurgel/tentacat#113]
It seems that the only methods linked to the labels on issues at the moment are [adding and listing labels](https://hexdocs.pm/tentacat/Tentacat.Issues.Labels.html).

I'm looking to use the [remove label api](https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue), would this be a good addition to Tentacat?

**Comment by SimonLab** [comment]
the remove method has been added with this last commits: #114 and https://github.com/edgurgel/tentacat/commit/ff1c4d58515ccf5527cb87a00fb461d0815c8dfc
Thanks

**Comment by edgurgel** [comment]
Thanks again!
