### ISSUE TITLE
testing guide in the readme

### ISSUE THREAD

**Issue by johannesE** [edgurgel/tentacat#118]
Almost all software needs tests. This could therefore help a lot of people.
I agree with Jose that mocking is not the best solution (http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/) and therefore think a behaviour-based approach could work best. This means that we have one module which we can exchange in the test environment for another behaviour. Behaviours in elixir can be seen like inheritance in other languages.
So in our tests, we would probably have a genserver store the items (in an :ets-table ?) we need and return them if the business logic asks for them. In dev and production, the tentacat wrapper would ask the other behaviour which works as usual.

Another possibility would be to create a test package just like they are doing here: https://github.com/code-corps/stripity_stripe/issues/124

I will try to find a solution within the next days and would love to get some input here. When I'm finished I'll make a PR to update the readme.

**Comment by edgurgel** [comment]
I completely disagree. I don't think we should change code so that tests are approachable. The API is fine as it is and I honestly don't see the reason to change. 

You can always apply the same thing you are proposing to your own code. Simply do DI and swap `Tentacat` with your preferred module to be your "mock". Wouldn't this be sufficient to test your business logic?

**Comment by johannesE** [comment]
Apparently I did not clearly say what I want to do. The goal of this is to have a guide as how to test business logic that uses tentacat. The goal is **not** to change the API. The guide should contain the best practice and have a short section in the readme..
> Simply do DI

What does DI stand for?
> swap Tentacat with your preferred module to be your "mock"

I guess that's what I'm gonna do. The only challenge is how to store the items, so that when I use the mock, it's returning me the correct ones. I will probably use a genserver that stores all the items in an :ets table. E.g. in my test setup I want to specify that I have 3 public repos and one private one. one of the repos has 1 open issue. etc. Then I can test that I'll have those things in the database after I call the corresponding method.

**Comment by edgurgel** [comment]
Yeah but why maintain a section so generic?  I would prefer to keep the README simple focused on Tentacat and not on Elixir development in general. I don't think every elixir library should explain how to write tests :/

**Comment by johannesE** [comment]
I was going to focus on how to write tentacat specific tests, but okay, I see that you do not like the idea. 😅 Your repo, your choice.
I'll write a blog post instead. 😛
