### ISSUE TITLE
GitHub response pagination

### ISSUE THREAD

**Issue by BachirC** [edgurgel/tentacat#120]
How is pagination handled by Tentacat ? 

I didn't find any mention of it in the documentation. [These tests](https://github.com/edgurgel/tentacat/blob/master/test/repositories_test.exs#L27) gave me some insight but I would like a more thorough answer :)

**Comment by bryanhuntesl** [comment]
@BachirC 

By selecting the configured pagination option :  

https://github.com/edgurgel/tentacat/blob/d4c9ba7d8dbc4825d43e5f4a5b0ce7698688b0e4/lib/tentacat.ex#L49-L62

And then by reading the github header and paging through, or returning a lazy loaded [Stream](https://hexdocs.pm/elixir/Stream.html)

```
Link: <https://api.github.com/user/818053/repos?page=2>; rel="next", <https://api.github.com/user/818053/repos?page=6>; rel="last"
```

https://github.com/edgurgel/tentacat/blob/d4c9ba7d8dbc4825d43e5f4a5b0ce7698688b0e4/lib/tentacat.ex#L141-L151

https://github.com/edgurgel/tentacat/blob/d4c9ba7d8dbc4825d43e5f4a5b0ce7698688b0e4/lib/tentacat.ex#L95-L118

**Comment by bryanhuntesl** [comment]
Suggest close this issue.
