### ISSUE TITLE
Support to  Github Http Redirects

### ISSUE THREAD

**Issue by micheldoumit** [edgurgel/tentacat#121]
When there is a 301 response from Github V3 Api an error is raised, in my understanding the redirect would have to be performed transparently.

The error I'm getting:

```
** (FunctionClauseError) no function clause matching in :lists.flatten/1
2017-09-06T15:20:05.510733+00:00 app[worker.1]:     (stdlib) lists.erl:616: :lists.flatten({301, %{"documentation_url" => "https://developer.github.com/v3/#http-redirects", "message" => "Moved Permanently", "url" => "https://api.github.com/repositories/28398133/pulls?state=open"}})
```
As you can see the "repos" was replaced by "repositories".

I'm running this code:
```ex
Tentacat.Pulls.filter(org, repo, %{state: "open"}, client)
```

See more:

https://developer.github.com/v3/#http-redirects

**Comment by duksis** [comment]
thanks @micheldoumit for reporting 
we should update the urls to use "repositories" instead of "repos" and make sure redirects are being handled - for 301's could also be useful to display a warning before redirecting.

**Comment by micheldoumit** [comment]
I did a little more digging, I got that redirect because the organization was renamed, I think both `repos` and `repositories` works, the issue is only the redirect handling that should be implemented.
