### ISSUE TITLE
passing the etag in requests

### ISSUE THREAD

**Issue by bryanhuntesl** [edgurgel/tentacat#135]
Hi, I'm going to drop down to HTTPoison most likely for this, one optimization which can be made in any call is to pass the ETag from the previous invocation - if you do so, and nothing has changed, your rate limit remains unchanged. Could it be passed in the existing options block? 

"ETag", "\"eaa46eb91c77ded86b4261245e49fbd5\"

**Comment by edgurgel** [comment]
We can probably accept `etag` as an option I think

**Comment by bryanhuntesl** [comment]
Ah, I've just hit this again - I'm trying to add repository polling functionality - if you pass the etag on subsequent requests it doesn't affect your rate limit.

I would need to modify the following code block - 

https://github.com/edgurgel/tentacat/blob/56c1f759e335d78d22e51b192a284f2e0dc2c547/lib/tentacat.ex#L58-L85

I'm trying to think of the way of doing so that's least disruptive, create another get function with an extra headers parameter ? 

Basically, it's pretty trivial - I'm trying to add the following functionality (which will work): 

```elixir
defmodule Tentacat.Repositories.Events do
  import Tentacat
  alias Tentacat.Client

  def list(client \\ %Client{}, owner, repo, latest_event_id ) do
    stream = get("repos/#{owner}/#{repo}/events", client, [], [pagination: :stream])
    stream |> Stream.take_while(fn(x) -> String.to_integer(x["id"])  >  latest_event_id end) |> Enum.to_list
  end

end
```

But if I could make it work like this, it would be even better : 

```elixir
defmodule Tentacat.Repositories.Events do
  import Tentacat
  alias Tentacat.Client

  def list(client \\ %Client{}, owner, repo, latest_event_id, etag ) do
    stream = get("repos/#{owner}/#{repo}/events", client, [], [pagination: :stream, request_headers: %{"ETag" => etag } ])
    stream |> Stream.take_while(fn(x) -> String.to_integer(x["id"])  >  latest_event_id end) |> Enum.to_list
  end

end
```

**Comment by bryanhuntesl** [comment]
`:streaming` throws away the headers - we'll have to use `:manual`
