### ISSUE TITLE
Tag + Release Tentacat 0.9

### ISSUE THREAD

**Issue by outofambit** [edgurgel/tentacat#142]
it looks like the release has been incremented in the repo (in light of the API change from #132) but it has not been tagged or released. can that be published to hex so we can use it? The standardized return type would be very helpful! thank you!

**Comment by edgurgel** [comment]
Yes! Sorry for the delay! I'm planning to do this today!

**Comment by outofambit** [comment]
Thank you @edgurgel! 😸
