### ISSUE TITLE
0.9.0 API is inconsistent. Some requests still return body instead of tuple {code, body, response}

### ISSUE THREAD

**Issue by smetana** [edgurgel/tentacat#144]
```elixir
Tentacat.Organizations.list_mine(client) # returns tuple
Tentacat.Repositories.list_mine(client) # returns list
```

**Comment by edgurgel** [comment]
Yes that's a bug! We should always return the tuple! Thanks for creating the issue

**Comment by defsprite** [comment]
I took a quick look at this, but it does not seem to be straightforward to fix for me (and record a test), since it is definitely related to pagination.

**Comment by defsprite** [comment]
As far as I can work it out from the test, this seems to be intended behaviour for functions that take pagination options.

- `pagination: :none` will return the expected `{status, body, response}` tuple.
- `pagination: nil` and `pagination: :auto` will return a list of all resulting elements, going through all pages automagically.
- `pagination: :stream` will return an `Enumerable` function constructed from `Stream.resource`.
- `pagination: :manual` will return a `{{status, body, response}, next_link, auth}` tuple.

This is definitely surprising behaviour at least for @smetana and me. But changing it could break things for a lot of people.

First of all, should I document this? Secondly, what to do about it? 
@edgurgel Any ideas?

**Comment by outofambit** [comment]
I have a fix for the original issue in this thread (returning lists instead of tuples). will open a pull request soon!

I'd suggest we open a new issue for the error tuple always getting returned so we can track that separately. (I think I can resolve that as well with a little more time)
