### ISSUE TITLE
feature to add repos to a team

### ISSUE THREAD

**Issue by lenfree** [edgurgel/tentacat#151]
Feature to add a repo/repos to a team. More info, please see below URL
https://developer.github.com/v3/teams/#add-or-update-team-repository

Sorry, Elixir newbie so I am unable to contribute right now.

**Comment by sreecodeslayer** [comment]
I think this can be closed in favor of https://github.com/edgurgel/tentacat/pull/156

**Comment by edgurgel** [comment]
True! Thanks @sreecodeslayer 👍
