### ISSUE TITLE
Undefined protocol?

### ISSUE THREAD

**Issue by Pedrosso** [edgurgel/tentacat#165]
Tentacat.Client.new (with & without credentials) works
Tentacat.Users.me(client) works

But more complicated functions like Tentacat.Users.find or Tentacat.Contents.find give me a "Protocol undefined error". Am I missing something?

![untitled](https://user-images.githubusercontent.com/32774583/52904007-f52c2300-3225-11e9-9f53-aec03fb1d522.png)

**Comment by Pedrosso** [comment]
I found the problem, the client & username parameters switched places, but this has not been changed yet in the example on the readme.

The function has to be written in this order:
Tentacat.Users.find Tentacat.Client.new, "edgurgel"

**Comment by edgurgel** [comment]
I see! Thanks for creating the issue 👍 We should definitely update the readme!

**Comment by braynm** [comment]
If the readme hasn't updated yet. I can update the readme and create a pull request. Thanks.

**Comment by edgurgel** [comment]
@braynm, that would be awesome!
