### ISSUE TITLE
support for Pulls.Reviews.create

### ISSUE THREAD

**Issue by fdb-hiroshima** [edgurgel/tentacat#174]
Hi, I was searching for how to use the endpoint described [here](https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review) in Tentacat, but I wasn't able to find anything.  Is is implemented yet?
(not related, the documentation can't be read online, it's dead link)

**Comment by edgurgel** [comment]
hey @fdb-hiroshima , I think that's what you are looking for https://github.com/edgurgel/tentacat/blob/master/lib/tentacat/pulls/review_requests.ex#L20-L38 ?

**Comment by edgurgel** [comment]
And thanks fro the heads-up! I will fix the documentation link 🤦‍♂

**Comment by fdb-hiroshima** [comment]
Hum, no, this does not appear to be it. The endpoint you point to is for asking someone for a review, where what I'm searching for is actually how to submit a review.
In all logic, if it was implemented, I'd expect to find it in this file https://github.com/edgurgel/tentacat/blob/master/lib/tentacat/pulls/reviews.ex , as both use the same endpoint with a different http verb

**Comment by edgurgel** [comment]
I see! Yeah this is missing! :(
