### ISSUE TITLE
migrate to Jason

### ISSUE THREAD

**Issue by bdubaut** [edgurgel/tentacat#185]
I am getting dependency conflicts with the `jsx` package version, which is required by `exjsx`.

Since the `exjsx` package is archived on GitHub, would it make sense to migrate the JSON encoding/decoding & serialization to `jason` ?

I understand it might come at a certain cost since `tentacat` uses `:jsx.json_term()` in the type specs, and it can also have an impact on the library's configuration options for deserialization.

**Comment by edgurgel** [comment]
Yeah let's use `Jason`!
