### ISSUE TITLE
Please add CHANGELOG

### ISSUE THREAD

**Issue by egze** [edgurgel/tentacat#198]
Please add a changelog to the project. It is always very convenient to look for changes if such file exists.

Thanks! Your library is great!

**Comment by edgurgel** [comment]
Yeah I will see if I can find a GH action that sends a PR with the updated Changelog based on the releases https://github.com/edgurgel/tentacat/releases

**Comment by edgurgel** [comment]
At the moment I suggest people using the GitHub Releases as the changelog until this is automated.
