### ISSUE TITLE
Question regarding dealing with automatically paging queries...

### ISSUE THREAD

**Issue by redvers** [edgurgel/tentacat#203]
When I call a function like Tentacat.Issues.list it automatically blocks until all the pages are downloaded.  This is awesome - except if possible I'd like some kind of indication as to how it's going.

If there isn't a way to increase the verbosity - could we maybe get an optional callback that's called every time a HTTP request is made so we can instrument something.

Thanks,

Red

**Comment by edgurgel** [comment]
Hi @redvers , have you checked the pagination options and see if one of those satisfy your requirements? https://hexdocs.pm/tentacat/Tentacat.html#get/4

**Comment by mustela** [comment]
Hey there! Im trying to set `pagination: :none` to the `filter` function from the Pull module, but I I can't make this work... is it not available at that level? 

```
Tentacat.Pulls.filter(client(), "myrepo", repository, %{
        "state" => "close",
        "per_page" => 1,
        "page" => 1,
        "pagination" => "none"
      })
```

Thanks
