### ISSUE TITLE
Timeout Settings

### ISSUE THREAD

**Issue by chaseconey** [edgurgel/tentacat#209]
Hello there 👋 .

I dug through the code and didn't see a way to configure any type of timeout for the response back from Github. It looks as though Github has a timeout of 10 seconds, but the timeout of this client seems to be much lower in using it. Is there a native way to adjust the timeout period?

Thanks!

**Comment by skipi** [comment]
:wave: You can set request [options](https://hexdocs.pm/httpoison/HTTPoison.Request.html) for underlying `HTTPoison` client like this:

```elixir
config :tentacat,
  request_options: [
    timeout: :timer.seconds(15),
    recv_timeout: :timer.seconds(10)
  ]
```

There are more options you can set as stated in [the docs](https://hexdocs.pm/tentacat/getting-started.html#configuration).
