### ISSUE TITLE
Pagination in Requests

### ISSUE THREAD

**Issue by nelsonic** [edgurgel/tentacat#210]
Hi! 👋 
Trying to use `tentacat` to retrieve a list of Org Members from `GitHub`. 🤞 
The API endpoint for **List organization members**: 
https://docs.github.com/en/rest/orgs/members#list-organization-members
Includes a **`page`** option to paginate the results.
We are trying to retrieve a list of members from an Org that has several hundred
and therefore we need to fetch multiple pages ...

Our reading of the `Tentacat.Organizations.Members.list/2` docs/code:
https://github.com/edgurgel/tentacat/blob/dfe89f33350acdf1ddea4a6f4d4338932fca0875/lib/tentacat/organizations/members.ex#L5-L21

It _appears_ to only allow passing the `client` and `organisation`, i.e. **no `page`** ... 🤷‍♂️ 
Can someone please confirm our understanding and inform if there is a way to request **`page=2`** of the results? ✌️ 
Thanks very much! 🙏

**Comment by edgurgel** [comment]
Hi there! Yeah we might need to accept a third argument `options` where you can pass `page: 1`, role or whatever other option this endpoint accepts

**Comment by nelsonic** [comment]
PR: https://github.com/edgurgel/tentacat/pull/220/files
