### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by dmarcoux** [edgurgel/tentacat#212]
Hello,

thank you for creating this project. I would like to know if it is still actively maintained since issues and PRs are left unanswered. While I can totally understand that priorities change, I wonder if you would be interested in getting help with maintaining the project?

**Comment by edgurgel** [comment]
Hi Dany! The project is still actively maintained (when I have time) and I'm always happy to receive help to maintain the project.

**Comment by vitalis** [comment]
Hi @edgurgel , if the project is still actively maintained what is the reason for so many open issues? 
If you need help to maintain the project please share the best option for you.
Thank you

**Comment by edgurgel** [comment]
Hi @vitalis! Nothing special here is happening. People can open as many issues as they want but if no one is sending PRs to solve them they will stay opened 🤷‍♂️ 

The project is open to receive PRs with solutions like most open source projects out there. If there are PRs that are ready and I missed I'm happy to look at again and merge it.
