### ISSUE TITLE
Using codebase for other APIs

### ISSUE THREAD

**Issue by trenpixster** [edgurgel/tentacat#33]
Hey @edgurgel! Good job with this wrapper for Github, I've been using it and it's really helpful. Is it ok to use this codebase to create other client APIs? What do you deem necessary, besides including your name on `LICENSE`? Thanks!

**Comment by edgurgel** [comment]
Hey @trenpixster, feel free to use however you want. The chosen license (MIT) requests that users should include the copyright and the original license and that's it.

Is this suitable for your use case?

**Comment by trenpixster** [comment]
Great! Yeah, it fits perfectly. Here's the link for the [LICENSE](https://github.com/trenpixster/asanaficator/blob/master/LICENSE). Looks good?

**Comment by edgurgel** [comment]
Looks great :+1:

**Comment by trenpixster** [comment]
Thanks again :+1:
