### ISSUE TITLE
Client.new/0 is undefined

### ISSUE THREAD

**Issue by cschiewek** [edgurgel/tentacat#34]
Brand new Elixir project, with just Tentacat as a dependency:

```shell
%  iex -S mix
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Tentacat.start
{:ok, [:idna, :hackney, :httpoison]}
iex(2)> client = Tentacat.Client.new
** (UndefinedFunctionError) undefined function: Tentacat.Client.new/0
    Tentacat.Client.new()
iex(2)>
```

Thoughts?

**Comment by edgurgel** [comment]
Which version are you using?  0.1.5 does not have this function. 

I will release a new version soon with this unreleased addition.

You can use `client = %Tentacat.Client{}` with 0.1.* 

I will close this issue when the release is done. I will probably also add the documentation to hexdocs so we can easily notice what's there and what's not.

**Comment by edgurgel** [comment]
https://hex.pm/packages/tentacat/0.2.0
