### ISSUE TITLE
commit comments?

### ISSUE THREAD

**Issue by joelmccracken** [edgurgel/tentacat#40]
I'm porting a script that I wrote with octokit.rb to tentacat, and found an important part (for me) of the gh api missing, specifically, commit comments. I can't find it documented in the github api documentation, but this method is available here:

https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/commit_comments.rb#L24

Is this something that tentacat would want to support?

**Comment by edgurgel** [comment]
Sure! Do you want to send a PR? :+1:

**Comment by joelmccracken** [comment]
Sure. Can't say when it'll happen, but its on my radar.

**Comment by ajorgensen** [comment]
I haven't had time to really test this yet but it should be a good start: https://github.com/edgurgel/tentacat/pull/42

**Comment by duksis** [comment]
Closing as #42 covers the github commit comments api and #49 adds test for it
