### ISSUE TITLE
0.3.0 release misses some commits

### ISSUE THREAD

**Issue by ghedamat** [edgurgel/tentacat#53]
hi again @edgurgel 

I saw that you release 0.3.0 and since #48 got merged I just tried to update my project to use tentacat from hex.

Weirdly, it looks like the 0.3.0 tag (and I presume also the pushed release) doesn't have all the commits and misses the merge of #48 

https://github.com/edgurgel/tentacat/commits/v0.3.0 

let me know if I can do anything else,

thanks!

**Comment by edgurgel** [comment]
I will simply release 0.3.1 with everything and we will be fine :)

**Comment by edgurgel** [comment]
Done: https://github.com/edgurgel/tentacat/releases/tag/v0.3.1 & https://hex.pm/packages/tentacat/0.3.1

**Comment by ghedamat** [comment]
thanks! still wonder what happened though :D
