### ISSUE TITLE
 Allow that `Tentacat.Repositories.list_mine/1` function also receives a set of options (based on possible github options)

### ISSUE THREAD

**Issue by cabol** [edgurgel/tentacat#55]
It would be good if `Tentacat.Repositories.list_mine/1` function also received a set of github options. These options would give it flexibility, and help filtering results -- as sometimes it's necessary.

I forked your repo and made the change, take a look at it:
https://github.com/cabol/tentacat/blob/master/lib/tentacat/repositories.ex#L21

I sent you the PR too.

Thanks.

**Comment by duksis** [comment]
Thanks @cabol - closing this as #56 was merged
