### ISSUE TITLE
Argument error when running mix test

### ISSUE THREAD

**Issue by juddey** [edgurgel/tentacat#58]
Following on from #57, I'm still having no luck trying to run tests :disappointed:.... I have 15 failures, all along the same line. Heres one:
```
 15) test remove/4 (Tentacat.Pulls.CommentsTest)
     test/pulls/comments_test.exs:56
     ** (ArgumentError) argument error
     stacktrace:
       (jsx) src/jsx_decoder.erl:234: :jsx_decoder.value/4
       (exjsx) lib/jsx.ex:15: JSX.decode!/2
       (tentacat) lib/tentacat.ex:13: Tentacat.process_response/1
       test/pulls/comments_test.exs:58
```

```
Finished in 7.5 seconds (0.5s on load, 6.9s on tests)
105 tests, 15 failures
```

While trying to solve this I have removed and reinstalled erlang via apt-get according to the Ubuntu instructions here: http://elixir-lang.org/install.html#unix-and-unix-like

```
justin@linisox:~/projects/tentacat$ elixir -v
Erlang/OTP 18 [erts-7.2] [source-e6dd627] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.0
```

The good news is that I have prototyped the search addition, it seems to work, so will write some tests and post the PR once this is resolved. :smile:

**Comment by duksis** [comment]
So If I understand that correctly even after reinstalling erlang and elixir you can't get the test passing?
If so could you let me know which Ubuntu version you are running?

**Comment by juddey** [comment]
Yep, that's right. Running Ubuntu 14.04 LTS.

```
uname -r
3.13.0-49-generic
```

**Comment by duksis** [comment]
@juddey thanks for reporting this. managed to reproduce thanks to travis-ci and a fix is on the way.
