### ISSUE TITLE
is there a way to provide self-signed CA certificates?

### ISSUE THREAD

**Issue by killerswan** [edgurgel/tentacat#66]
I'm seeing this from `Tentacat.Commits.find` with a GHE using a self-signed CA:
```
19:02:06.119 [error] SSL: :certify: ssl_handshake.erl:1490:Fatal error: unknown ca

** (HTTPoison.Error) {:tls_alert, 'unknown ca'}
    (tentacat) lib/tentacat.ex:2: Tentacat.request!/5
    (tentacat) lib/tentacat.ex:42: Tentacat.json_request/5
```

I believe HTTPoison's `request!/5` (which is used in Tentacat, e.g., [here](https://github.com/edgurgel/tentacat/blob/master/lib/tentacat.ex#L42)) takes some kind of list of options where I could specify a "cacertfile" path...

If not for https://github.com/edgurgel/tentacat/issues/65 I'd try that, but is there an easier way to just override some HTTPoison default setting and provide a CA cert in my own project's `config.exs`?

**Comment by duksis** [comment]
I assume that this can be closed as #69 is merged. Thanks @killerswan !
