### ISSUE TITLE
Error trying to record response with exvcr

### ISSUE THREAD

**Issue by alemata** [edgurgel/tentacat#79]
Hi @edgurgel, 

I am trying to write a test, which call to `Tentacat.Repositories.list_mine(client)` using [exvcr](https://github.com/parroty/exvcr), but I am getting an error:

```
stacktrace:
       (stdlib) gen.erl:168: :gen.do_call/4
       (elixir) lib/gen_server.ex:561: GenServer.call/3
       lib/exvcr/handler.ex:24: ExVCR.Handler.get_response_from_cache/2
       lib/exvcr/handler.ex:14: ExVCR.Handler.get_response/2
       src/meck_code_gen.erl:154: :meck_code_gen.exec/4
       (httpoison) lib/httpoison/base.ex:396: HTTPoison.Base.request/9
       (tentacat) lib/tentacat.ex:2: Tentacat.request!/5
       (tentacat) lib/tentacat.ex:110: Tentacat.request_with_pagination/4
```

As you use the same lib to record http responses, perhaps you know what's going on here.
Thanks!

**Comment by duksis** [comment]
@alemata have you tried to configure the cassette to match request only on query?
like here [test/users_test.exs#L29](https://github.com/edgurgel/tentacat/blob/47e75f4a683e68d32964972c90398554e6c5ebe0/test/users_test.exs#L29)
