### ISSUE TITLE
Does tentacat support anything for registering webhooks?

### ISSUE THREAD

**Issue by fire** [edgurgel/tentacat#90]
Is this the correct library to listen for webhook responses?

**Comment by edgurgel** [comment]
@fire, if I understood well you want to *receive* the webhook instead of creating/listing/deleting them. Tentacat wasn't meant to be used as part of the receiving part. Although it should be pretty straightforward to build an HTTP endpoint inside your server to receive these events with payloads.

**Comment by fire** [comment]
If you describe briefly how, that could work, I would be grateful. 

Trying to create a "chat bot" that listens to github issue / pr comments and then does tasks.

**Comment by edgurgel** [comment]
Here's the official documentation: https://developer.github.com/webhooks/

As you can see it's a single endpoint that you need to create. There's an example on how to start something

**Comment by Marqin** [comment]
I hope little advertise is not forbidden.
@fire, [this](https://github.com/Marqin/tentahook) is my simple webhook library in Elixir (Zlib license).

**Comment by edgurgel** [comment]
Awesome, @Marqin. Thanks for sharing 👍
