### ISSUE TITLE
Idiomatic elixir would have the client as the first argument in api

### ISSUE THREAD

**Issue by joelmccracken** [edgurgel/tentacat#98]
One surprising thing about using tentacat is that the client argument is always the last item in function argument lists.

From the README, it would be better if we could do:

```
iex> Tentacat.Client.new |> Tentacat.Users.find "edgurgel", client
```

Instead of:

```
iex> client = Tentacat.Client.new
iex> Tentacat.Users.find "edgurgel", client
```

**Comment by edgurgel** [comment]
It would be idiomatic if the module you were using is talking about the client but it's about users. The first argument is the `user` not the client. Also the client is optional as there's no need for one if you are not using auth for example.
